"""
sample_sheet.py
===============
Parse per-well sample sheets for Smart-seq / FLASH-seq plate runs.

Supported formats
-----------------
The parser is intentionally flexible — it detects columns by content rather
than requiring a fixed schema.  Two common formats are handled:

Format A — separate PlateID / WellID columns (generated by some LIMS):
  PlateID, WellID, i5_Name, i7_Name, i5_Sequence, i7_Sequence

Format B — combined Sample_Name column (most common; mirrors the folder names
  that STAR / bcl2fastq produce):
  Sample_Name, i7 sequence, i5 reverse complement (NovaSeq)

In both cases the parser finds i5 and i7 columns by looking for "i5" and "i7"
anywhere in the column header (case-insensitive).  Column order does not matter.

Column detection rules
----------------------
- The key column is either "Sample_Name" (split on last _ before the well
  coordinate) or separate "WellID" / "PlateID" columns.
- i7 column: any header containing "i7" (case-insensitive).
- i5 column: any header containing "i5" (case-insensitive).
- Ambiguity (multiple i5 or i7 columns): the first match is used and a warning
  is logged.

i7 / i5 orientation
--------------------
Some sequencer platforms read the i7 index via the opposite strand, so the
FASTQ index read (and bcl2fastq sample sheet) contains the reverse complement
(RC) of the designed oligo.

  Platform            i7 FASTQ    i5 FASTQ
  -----------------   ---------   ---------
  NextSeq 500/550     RC          RC
  NextSeq 1000/2000   RC          RC
  NovaSeq 6000        forward     RC
  NovaSeq X / X+      RC          RC
  Element AVITI       forward     forward

The --sequencer flag controls i7 orientation.  Additionally, if the column
header for i5 contains "reverse complement" or " rc" (case-insensitive), the
tool assumes the i5 stored in the CSV is already RC-oriented and reports it
as-is (no further transformation).

Note for NovaSeq users: your sample sheet likely has the i5 column labelled
"i5 reverse complement (NovaSeq)" — that value is already the correct sequence
for bcl2fastq.  Pass --sequencer novaseq; the i5 will be used as stored.
"""

from __future__ import annotations

import csv
import itertools
import logging
import re
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

# Sequencers whose i7 FASTQ index is the RC of the designed oligo.
# True  → i7 stored in CSV is the FASTQ / sample-sheet sequence; RC it back
#          to recover the designed orientation for display.
# False → i7 stored in CSV is already the designed / forward orientation.
_SEQUENCER_I7_IS_RC: dict[str, bool] = {
    "nextseq":  True,    # NextSeq 500/550/1000/2000
    "novaseq":  False,   # NovaSeq 6000 (i7 forward, i5 RC)
    "novaseqx": True,    # NovaSeq X / X Plus
    "aviti":    False,   # Element AVITI
    "none":     False,
    "auto":     False,
}

# Well coordinate pattern — matches A1 … P24 (96- and 384-well plates)
_WELL_RE = re.compile(r"^([A-Pa-p])(\d{1,2})$")

_COMPLEMENT = str.maketrans("ACGTacgt", "TGCAtgca")


def _rc(seq: str) -> str:
    """Return the reverse complement of *seq*."""
    return seq.translate(_COMPLEMENT)[::-1]


def _find_col(headers_lower: list[str], marker: str) -> Optional[int]:
    """
    Return the index of the first header that contains *marker* (case-insensitive).
    Returns None if no match is found.
    """
    for i, h in enumerate(headers_lower):
        if marker in h:
            return i
    return None


def _split_sample_name(name: str) -> tuple[str, str]:
    """
    Split a Sample_Name like "881_A1" into (plate_id, well_id).

    The last underscore-delimited token that looks like a well coordinate
    (letter + 1-2 digits) is treated as the well; everything before it is
    the plate ID.

    Returns ("", name) if no well coordinate is found.
    """
    parts = name.rsplit("_", 1)
    if len(parts) == 2 and _WELL_RE.match(parts[1]):
        plate = parts[0]
        well  = parts[1].upper()
        return plate, well
    return "", name.upper()


def parse_sample_sheet(
    path: str | Path,
    sequencer: str = "none",
) -> dict[str, dict]:
    """
    Parse a per-well CSV and return a dict keyed by canonical well ID.

    Column detection is done by content (case-insensitive substring match),
    so neither a fixed schema nor a specific column order is required.

    Parameters
    ----------
    path:
        Path to the CSV file (plain text; BOM is stripped automatically).
    sequencer:
        Sequencer platform key (see module docstring).  Controls whether the
        i7 sequence stored in the CSV is treated as forward (designed) or
        reverse-complemented (FASTQ orientation) and needs to be RC'd back.

    Returns
    -------
    dict mapping canonical key → metadata dict.

    Canonical key format:
      - "PlateID/WellID"  when a plate ID is present (e.g. "881/A1")
      - "WellID"          when no plate information is found (e.g. "A1")

    Each value dict contains at minimum:
      well_id, plate_id, i7_seq, i5_seq
    and optionally i7_name / i5_name when dedicated name columns exist.
    Extra columns from the CSV are preserved verbatim.
    """
    path = Path(path)
    rc_i7 = _SEQUENCER_I7_IS_RC.get(sequencer.lower(), False)

    with open(path, newline="", encoding="utf-8-sig") as fh:
        reader = csv.reader(fh)
        raw_headers = next(reader)
        if not raw_headers:
            raise ValueError(f"Empty or header-less CSV: {path}")

        # Detect headerless files: if no cell matches a recognised column-name
        # token (exact match or hyphen/underscore-separated token), treat the
        # first row as data and assign default positional names.  Using
        # whole-token matching avoids false positives on data values that
        # happen to contain a keyword as a substring (e.g. "sample_output_123").
        _header_markers = {"sample", "well", "plate", "i5", "i7",
                           "name", "index", "sequence", "barcode",
                           "samplename", "sample_name", "wellid", "plateid"}

        def _header_tokens(cell: str) -> set:
            low = cell.strip().lower()
            tokens = {low}
            for sep in ("_", "-", " "):
                tokens.update(low.split(sep))
            return {t for t in tokens if t}

        _looks_like_header = any(
            _header_tokens(h) & _header_markers
            for h in raw_headers if h.strip()
        )
        if not _looks_like_header:
            logger.warning(
                "First row of '%s' contains no recognised column names — "
                "treating it as data. Columns assigned as: "
                "Sample_Name, i7_sequence, i5_reverse_complement. "
                "Add a header row to suppress this warning.",
                path.name,
            )
            _default = ["Sample_Name", "i7_sequence", "i5_reverse_complement"]
            n = len(raw_headers)
            _data_first_row = raw_headers  # original row is data, not headers
            raw_headers = _default[:n] + [f"col_{i}" for i in range(len(_default), n)]
            reader = itertools.chain([_data_first_row], reader)  # type: ignore[assignment]

        headers        = [h.strip() for h in raw_headers]
        headers_lower  = [h.lower() for h in headers]

        # ------------------------------------------------------------------ #
        # Detect key column (Sample_Name vs separate WellID/PlateID)
        # ------------------------------------------------------------------ #
        sample_name_idx = _find_col(headers_lower, "sample_name")
        well_id_idx     = _find_col(headers_lower, "wellid")
        plate_id_idx    = _find_col(headers_lower, "plateid")

        # Also accept "well" alone if there's no "wellid"
        if well_id_idx is None:
            well_id_idx = _find_col(headers_lower, "well")

        if sample_name_idx is None and well_id_idx is None:
            raise ValueError(
                f"Sample sheet must have either a 'Sample_Name' column "
                f"(PlateID_WellID format) or a 'WellID' column. "
                f"Found headers: {headers}"
            )

        # ------------------------------------------------------------------ #
        # Detect i7 and i5 columns
        # ------------------------------------------------------------------ #
        i7_idx = _find_col(headers_lower, "i7")
        i5_idx = _find_col(headers_lower, "i5")

        if i7_idx is None and i5_idx is None:
            raise ValueError(
                f"Sample sheet must have at least one column whose header "
                f"contains 'i7' or 'i5'. Found headers: {headers}"
            )

        # Detect name columns (e.g. "i7_Name", "i5 primer name")
        i7_name_idx = None
        i5_name_idx = None
        for i, h in enumerate(headers_lower):
            if "i7" in h and ("name" in h or "primer" in h or "label" in h):
                i7_name_idx = i
            if "i5" in h and ("name" in h or "primer" in h or "label" in h):
                i5_name_idx = i

        # Warn if multiple i7 or i5 columns found (first wins)
        i7_count = sum(1 for h in headers_lower if "i7" in h)
        i5_count = sum(1 for h in headers_lower if "i5" in h)
        if i7_count > 1:
            logger.warning(
                "Multiple i7 columns found in sample sheet — using '%s'.",
                headers[i7_idx],
            )
        if i5_count > 1:
            logger.warning(
                "Multiple i5 columns found in sample sheet — using '%s'.",
                headers[i5_idx],
            )

        # ------------------------------------------------------------------ #
        # Determine if i5 column is already RC-oriented from its header text
        # (e.g. "i5 reverse complement (NovaSeq)")
        # ------------------------------------------------------------------ #
        _i5_col_is_rc = False
        if i5_idx is not None:
            _h = headers_lower[i5_idx]
            if "reverse complement" in _h or " rc" in _h or "_rc" in _h:
                _i5_col_is_rc = True
                logger.info(
                    "i5 column '%s' appears to contain RC sequences (detected from header). "
                    "Storing as-is.",
                    headers[i5_idx],
                )

        # ------------------------------------------------------------------ #
        # Parse rows
        # ------------------------------------------------------------------ #
        def _cell(row: list, idx: Optional[int]) -> str:
            if idx is None or idx >= len(row):
                return ""
            return row[idx].strip()

        records: dict[str, dict] = {}
        skipped = 0
        n_duplicates = 0

        for row in reader:
            if not any(c.strip() for c in row):
                continue  # blank line

            # Resolve well and plate IDs
            if sample_name_idx is not None:
                sname = _cell(row, sample_name_idx)
                plate_id, well_id = _split_sample_name(sname)
            else:
                well_raw = _cell(row, well_id_idx)
                plate_id = _cell(row, plate_id_idx) if plate_id_idx is not None else ""

                # Handle row-letter + column-number split
                # If WellID is a single letter and there's a "column" column nearby
                col_idx = _find_col(headers_lower, "column")
                if col_idx is not None and len(well_raw) == 1 and well_raw.isalpha():
                    well_id = (well_raw + _cell(row, col_idx)).upper()
                else:
                    well_id = well_raw.upper()

            if not well_id:
                skipped += 1
                continue

            key = f"{plate_id.upper()}/{well_id}" if plate_id else well_id

            i7_seq = _cell(row, i7_idx) if i7_idx is not None else ""
            i5_seq = _cell(row, i5_idx) if i5_idx is not None else ""

            # Apply i7 RC if the sequencer stores it RC-oriented in the sheet
            if rc_i7 and i7_seq:
                i7_seq = _rc(i7_seq)

            record: dict = {
                "well_id":  well_id,
                "plate_id": plate_id.upper(),
                "i7_seq":   i7_seq,
                "i5_seq":   i5_seq,
                "i7_name":  _cell(row, i7_name_idx) if i7_name_idx is not None else "",
                "i5_name":  _cell(row, i5_name_idx) if i5_name_idx is not None else "",
            }
            # Carry through all other columns verbatim
            for idx, h in enumerate(headers):
                lh = h.lower()
                skip_h = {"sample_name", "wellid", "well", "plateid"}
                if (idx in {i7_idx, i5_idx, i7_name_idx, i5_name_idx,
                            sample_name_idx, well_id_idx, plate_id_idx}
                        or lh in skip_h):
                    continue
                record[h] = _cell(row, idx)

            if key in records:
                n_duplicates += 1
            records[key] = record  # last row wins

        if skipped:
            logger.warning(
                "Skipped %d rows in sample sheet with missing well ID.", skipped
            )
        if n_duplicates:
            logger.warning(
                "%d well(s) appeared more than once in the sample sheet with "
                "conflicting barcode sequences. The last row was kept for each. "
                "Check your sample sheet for duplicate Sample_Name entries.",
                n_duplicates,
            )

    logger.info(
        "Loaded sample sheet: %d wells%s (sequencer=%s, i7_rc=%s, i5_from_rc_col=%s)",
        len(records),
        " with plate IDs" if any("/" in k for k in records) else "",
        sequencer,
        rc_i7,
        _i5_col_is_rc,
    )
    return records


def lookup_well(
    sample_sheet: dict[str, dict],
    plate_id: str,
    well_id: str,
) -> Optional[dict]:
    """
    Return the metadata for (plate_id, well_id), or None if not found.

    Tries:
      1. "PlateID/WellID"  — multi-plate sheets
      2. "WellID"          — single-plate sheets (no plate column)
    """
    well_up  = well_id.upper()
    plate_up = plate_id.upper()

    combined = f"{plate_up}/{well_up}"
    if combined in sample_sheet:
        return sample_sheet[combined]
    if well_up in sample_sheet:
        return sample_sheet[well_up]
    return None
